import logging
import os
import tempfile

import anndata as ad
import numpy as np
import torch
from scipy.sparse import csc_matrix, issparse

import sciPENN.sciPENN_API as sciPENN_api_module
from sciPENN.sciPENN_API import sciPENN_API

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

## VIASH START
# The following code has been auto-generated by Viash.
par = {
  'input_train_mod1': r'resources_test/task_predict_modality/openproblems_neurips2021/bmmc_cite/swap/train_mod1.h5ad',
  'input_train_mod2': r'resources_test/task_predict_modality/openproblems_neurips2021/bmmc_cite/swap/train_mod2.h5ad',
  'input_test_mod1': r'resources_test/task_predict_modality/openproblems_neurips2021/bmmc_cite/swap/test_mod1.h5ad',
  'output': r'resources_test/task_predict_modality/openproblems_neurips2021/bmmc_cite/swap/prediction.h5ad',
  'n_epochs': int(r'10000'),
  'batch_size': int(r'128'),
  'select_hvg': r'true'.lower() == 'true',
  'min_cells': int(r'0'),
  'min_genes': int(r'0'),
  'seed': int(r'0')
}
meta = {
  'name': r'scipenn',
  'functionality_name': r'scipenn',
  'resources_dir': r'/private/tmp/viash_inject_scipenn9938836932697460781',
  'executable': r'/private/tmp/viash_inject_scipenn9938836932697460781/scipenn',
  'config': r'/private/tmp/viash_inject_scipenn9938836932697460781/.config.vsh.yaml',
  'temp_dir': r'/var/folders/xg/kg0ykmg958z6z1gyqzy7tk8r0000gn/T/',
  'cpus': int(r'123'),
  'memory_b': int(r'123'),
  'memory_kb': int(r'123'),
  'memory_mb': int(r'123'),
  'memory_gb': int(r'123'),
  'memory_tb': int(r'123'),
  'memory_pb': int(r'123'),
  'memory_kib': int(r'123'),
  'memory_mib': int(r'123'),
  'memory_gib': int(r'123'),
  'memory_tib': int(r'123'),
  'memory_pib': int(r'123')
}
dep = {
  
}

## VIASH END

logger.info("Reading input files...")
rna_train = ad.read_h5ad(par["input_train_mod1"])   # mod1 = RNA (GEX)
prot_train = ad.read_h5ad(par["input_train_mod2"])   # mod2 = protein (ADT)
rna_test = ad.read_h5ad(par["input_test_mod1"])

# sciPENN only supports the GEX -> ADT direction. It biologically interprets the
# gene sets as RNA and the protein sets as surface protein, so running it on the
# swapped (ADT -> GEX) direction produces meaningless output. Fail loudly instead.
mod1 = rna_train.uns.get("modality")
mod2 = prot_train.uns.get("modality")
if mod1 != "GEX" or mod2 != "ADT":
    raise ValueError(
        f"sciPENN only supports predicting protein (ADT) from RNA (GEX); "
        f"got mod1={mod1!r}, mod2={mod2!r}."
    )

np.random.seed(par["seed"])
torch.manual_seed(par["seed"])

# Feed sciPENN the task's log_cp10k layer (its internal normalize_total/log1p are
# disabled below) so predictions live in the same space as the ground truth. sciPENN
# never casts dtypes, and float64 input crashes its float32 BatchNorm layers.
for adata in (rna_train, prot_train, rna_test):
    adata.X = adata.layers["normalized"].astype(np.float32)

# sciPENN scales each batch independently with sc.pp.scale, which divides by (n - 1)
# and therefore fails on any batch with a single cell. Only use per-batch scaling when
# every non-empty batch in both train and test has at least 2 cells; otherwise fall
# back to global scaling (batch keys disabled).
def _batches_safe(*adatas):
    for a in adatas:
        if "batch" not in a.obs:
            return False
        counts = a.obs["batch"].value_counts()
        if (counts[counts > 0] < 2).any():
            return False
    return True

if _batches_safe(rna_train, rna_test):
    train_batchkeys = ["batch"]
    test_batchkey = "batch"
else:
    logger.warning(
        "Disabling per-batch scaling: a batch has fewer than 2 cells "
        "(sciPENN's per-batch sc.pp.scale would divide by zero)."
    )
    train_batchkeys = None
    test_batchkey = None

# sciPENN z-scores the protein targets (per batch or globally, as chosen above) with
# sc.pp.scale, so the model predicts z-scores. Record the training-protein mean/std over
# the same groups to map predictions back to log_cp10k. With global scaling this is the
# exact inverse; with per-batch scaling the test batches are unseen, so use the
# cell-weighted average of the per-batch statistics. Must run before sciPENN_API, which
# scales prot_train.X in place.
def _scale_stats(X):
    # Matches sc.pp.scale: ddof=1 std, zero std replaced by 1.
    std = X.std(axis=0, ddof=1)
    std[std == 0] = 1.0
    return X.mean(axis=0), std

prot_X = prot_train.X.toarray() if issparse(prot_train.X) else np.asarray(prot_train.X)
prot_X = prot_X.astype(np.float64)
if train_batchkeys is None:
    prot_mean, prot_std = _scale_stats(prot_X)
else:
    batches = prot_train.obs["batch"].to_numpy()
    groups = [batches == b for b in np.unique(batches)]
    stats = [_scale_stats(prot_X[g]) for g in groups]
    weights = np.array([g.sum() for g in groups], dtype=np.float64)
    weights /= weights.sum()
    prot_mean = sum(w * m for w, (m, _) in zip(weights, stats))
    prot_std = sum(w * s for w, (_, s) in zip(weights, stats))
del prot_X

# sciPENN 0.9.6's build_dir loops forever on absolute paths (os.path.split("/") never
# yields ""), appending "/" to a list until the process is OOM-killed.
sciPENN_api_module.build_dir = lambda path: os.makedirs(path, exist_ok=True)

# sciPENN auto-falls back to CPU, but pass the detected value explicitly.
use_gpu = torch.cuda.is_available()
logger.info("Using %s", "GPU" if use_gpu else "CPU")

logger.info("Constructing sciPENN model...")
weights_dir = tempfile.mkdtemp(prefix="scipenn_")
scipenn = sciPENN_API(
    gene_trainsets=[rna_train],
    protein_trainsets=[prot_train],
    gene_test=rna_test,
    train_batchkeys=train_batchkeys,
    test_batchkey=test_batchkey,
    select_hvg=par["select_hvg"],
    cell_normalize=False,
    log_normalize=False,
    min_cells=par["min_cells"],
    min_genes=par["min_genes"],
    batch_size=par["batch_size"],
    use_gpu=use_gpu,
)

logger.info("Training sciPENN...")
scipenn.train(n_epochs=par["n_epochs"], weights_dir=weights_dir, load=False)

logger.info("Predicting protein expression...")
imputed = scipenn.predict()   # .X = predicted protein z-scores

# Row space must equal the full test set, in the original order. With
# min_genes=min_cells=0 no cells are dropped, so verify the assumption holds.
if imputed.n_obs != rna_test.n_obs:
    raise RuntimeError(
        f"sciPENN returned {imputed.n_obs} cells but the test set has "
        f"{rna_test.n_obs}; QC filtering must be disabled (min_genes/min_cells=0)."
    )
if not np.array_equal(np.asarray(imputed.obs_names), np.asarray(rna_test.obs_names)):
    imputed = imputed[rna_test.obs_names].copy()

# Column space must equal input_train_mod2.var order. sciPENN may reorder/subset
# proteins, so scatter by name and zero-fill any protein it dropped (NaN would break
# the correlation/mse metrics).
imputed_X = np.asarray(imputed.X, dtype=np.float64) * prot_std + prot_mean
src_pos = {name: i for i, name in enumerate(imputed.var_names)}
target = list(prot_train.var_names)
preds = np.zeros((imputed.n_obs, len(target)), dtype=np.float32)
missing = []
for j, name in enumerate(target):
    k = src_pos.get(name)
    if k is not None:
        preds[:, j] = imputed_X[:, k]
    else:
        missing.append(name)
if missing:
    logger.warning("sciPENN dropped %d proteins; zero-filled: %s", len(missing), missing)

logger.info("Writing predictions...")
out = ad.AnnData(
    layers={"normalized": csc_matrix(preds)},
    obs=rna_test.obs[[]],
    var=prot_train.var[[]],
    uns={
        "dataset_id": rna_test.uns["dataset_id"],
        "method_id": meta["name"],
    },
)
out.write_h5ad(par["output"], compression="gzip")
logger.info("Predictions saved to %s", par["output"])
