__merge__: ../../api/comp_control_method.yaml
name: mean_per_gene
label: Mean per gene
summary: Returns the mean expression value per gene.
description: Returns the mean expression value per gene.
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, lowcpu]
  