__merge__: ../../api/comp_method.yaml
name: knnr_r
label: KNNR (R)
summary: K-nearest neighbor regression in R.
description: K-nearest neighbor regression in R.
references:
  doi: 10.2307/1403797
info:
  documentation_url: https://cran.r-project.org/package=FNN
  repository_url: https://github.com/cran/FNN
  preferred_normalization: log_cp10k
arguments:
  - name: "--distance_method"
    type: "string"
    default: "spearman"
    description: The distance method to use. Possible values are euclidean, pearson, spearman and others.
  - name: "--n_pcs"
    type: "integer"
    default: 50
    description: Number of principal components to use.
  - name: "--n_neighbors"
    type: "integer"
    default: 20
    description: Number of neighbors to use in the knn regression.
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1
    setup:
      - type: r
        cran: [ lmds, FNN, proxyC]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, midmem, midcpu]
