__merge__: ../../api/comp_metric.yaml
name: correlation
info:
  metrics:
    - name: mean_pearson_per_cell
      label: Mean pearson per cell
      summary: The mean of the pearson values of per-cell expression value vectors.
      description: The mean of the pearson values of per-cell expression value vectors.
      min: -1
      max: 1
      maximize: true
      references:
        doi: 10.1098/rspl.1895.0041
    - name: mean_spearman_per_cell
      label: Mean spearman per cell
      summary: The mean of the spearman values of per-cell expression value vectors.
      description: The mean of the spearman values of per-cell expression value vectors.
      min: -1
      max: 1
      maximize: true
      references:
        doi: 10.1093/biomet/30.1-2.81
    - name: mean_pearson_per_gene
      label: Mean pearson per gene
      summary: The mean of the pearson values of per-gene expression value vectors.
      description: The mean of the pearson values of per-gene expression value vectors.
      min: -1
      max: 1
      maximize: true
      references:
        doi: 10.1098/rspl.1895.0041
    - name: mean_spearman_per_gene
      label: Mean spearman per gene
      summary: The mean of the spearman values of per-gene expression value vectors.
      description: The mean of the spearman values of per-gene expression value vectors.
      min: -1
      max: 1
      maximize: true
      references:
        doi: 10.1093/biomet/30.1-2.81
    - name: overall_pearson
      label: Overall pearson
      summary: The mean of the pearson values of vectorized expression matrices.
      description: The mean of the pearson values of vectorized expression matrices.
      min: -1
      max: 1
      maximize: true
      references:
        doi: 10.1098/rspl.1895.0041
    - name: overall_spearman
      label: Overall spearman
      summary: The mean of the spearman values of vectorized expression matrices.
      description: The mean of the spearman values of vectorized expression matrices.
      min: -1
      max: 1
      maximize: true
      references:
        doi: 10.1093/biomet/30.1-2.81
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1
    setup:
      - type: r
        cran: [ proxyC, testthat, dynutils ]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, lowmem, lowcpu]
