__merge__: ../../../api/comp_method_predict.yaml
name: senkin_predict
resources:
  - path: script.py
    type: python_script
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    setup:
      - type: docker
        run: pip install --no-cache-dir --no-deps git+https://github.com/lueckenlab/senkin-tmp-cite-pred.git
      - type: python
        packages:
          - lightgbm>=4.0
          - tensorflow>=2.12
          - scikit-learn>=1.1
          - mudata>=0.2
          - muon>=0.1
          - fast-array-utils
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, hightime, midcpu, gpu]
