__merge__: ../../../api/comp_method_predict.yaml
name: senkin_predict

info:
  test_setup:
    with_model:
      input_test_mod1: resources_test/task_predict_modality/openproblems_neurips2021/bmmc_cite/normal/test_mod1.h5ad
      input_train_mod2: resources_test/task_predict_modality/openproblems_neurips2021/bmmc_cite/normal/train_mod2.h5ad
      input_model: resources_test/task_predict_modality/openproblems_neurips2021/bmmc_cite/normal/models/senkin/model.pkl
resources:
  - path: script.py
    type: python_script
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    setup:
      - type: docker
        run: pip install --no-cache-dir --no-deps git+https://github.com/lueckenlab/senkin-tmp-cite-pred.git
      - type: python
        packages:
          - lightgbm>=4.0
          - tensorflow>=2.12
          - scikit-learn>=1.1
          - mudata>=0.2
          - muon>=0.1
          - fast-array-utils
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, hightime, midcpu]
