__merge__: ../../api/comp_method.yaml
name: cellmapper_linear
label: CellMapper+PCA/CCA
summary: "Modality prediction in a PCA/CCA space using CellMapper"
description: |
  CellMapper is a general framework for k-NN based mapping tasks in single-cell and spatial genomics.
  This variant uses CellMapper to project modalities from a reference dataset (train) onto a query dataset (test) in a PCA/CCA latent space.
references:
  doi: 
    - 10.5281/zenodo.15683594
links:
  documentation: https://cellmapper.readthedocs.io/en/latest/
  repository: https://github.com/quadbio/cellmapper
info:
  preferred_normalization: log_cp10k
  variants: 
    cellmapper-pca:
      fallback_representation: joint_pca
      mask_var: None
      kernel_method: hnoca
    cellmapper-pca-hvg:
      fallback_representation: joint_pca
      mask_var: "hvg"
      kernel_method: hnoca
    cellmapper-pca-hvg-gauss:
      fallback_representation: joint_pca
      mask_var: "hvg"
      kernel_method: gauss
    cellmapper-cca:
      fallback_representation: fast_cca
      mask_var: None
      kernel_method: hnoca
    cellmapper-cca-hvg:
      fallback_representation: fast_cca
      mask_var: "hvg"
      kernel_method: hnoca
    cellmapper-cca-hvg-gauss:
      fallback_representation: fast_cca
      mask_var: "hvg"
      kernel_method: gauss
arguments:
  - name: "--fallback_representation"
    type: "string"
    choices: ["joint_pca", "fast_cca"]
    default: "joint_pca"
    description: Fallback representation to use for k-NN mapping (computed if use_rep is None).
  - name: "--mask_var"
    type: "string"
    default: "hvg"
    description: Variable to mask for fallback representation.
  - name: "--kernel_method"
    type: "string"
    choices: ["hnoca", "gauss"]
    default: "gauss"
    description: Kernel function to compute k-NN edge weights. 
  - name: "--n_neighbors"
    type: "integer"
    default: 50
    description: Number of neighbors to consider for k-NN graph construction.
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: python
        packages: 
          - cellmapper>=0.2.2
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
