__merge__: ../../api/comp_method.yaml

name: ss_opm
label: SS-OPM
summary: t-SVD-based imputation by Shuji Suzuki
description: |
  A t-SVD-based imputation method developed as part of the OpenProblems NeurIPS2022 multimodal challenge.
references:
  doi: []
    # - TODO: 10.1000/xx.123456.789
links:
  documentation: https://www.kaggle.com/competitions/open-problems-multimodal/discussion/366961
  repository: https://github.com/shu65/open-problems-multimodal

info:
  preferred_normalization: log_cp10k

resources:
  - type: bash_script
    path: script.sh

engines:
  - type: docker
    image: python:3.10
    setup:
      # copied from openproblems-bio/core:
      - type: apt
        packages:
          - procps
          - git
          - unzip
      - type: python
        packages:
          - anndata~=0.10.0
          - scanpy~=1.10.0
          - pyyaml
          - requests
          - jsonschema
        github:
          - openproblems-bio/core#subdirectory=packages/python/openproblems
      # dependencies for this method:
      - type: docker
        run: 
          - git clone https://github.com/shu65/open-problems-multimodal.git /opt/shu65_openproblems && pip install --editable /opt/shu65_openproblems
          - wget https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt -O "/opt/hgnc_complete_set.txt"
          - wget https://reactome.org/download/current/ReactomePathways.gmt.zip -O "/opt/ReactomePathways.gmt.zip" &&
              unzip "/opt/ReactomePathways.gmt.zip" -d "/opt" &&
              rm "/opt/ReactomePathways.gmt.zip"

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
