__merge__: ../../api/comp_control_method.yaml
name: zeros
label: Zeros
summary: Returns a prediction consisting of all zeros.
description: Returns a prediction consisting of all zeros.
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, lowcpu]
