__merge__: /src/api/comp_process_datasets.yaml
name: "process_datasets"
namespace: "workflows"
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf
dependencies:
  - name: schema/verify_data_structure
    repository: core
  - name: h5ad/extract_uns_metadata
    repository: core
  - name: data_processors/process_dataset
runners:
  - type: nextflow
