__merge__: /src/api/comp_process_datasets.yaml
name: "process_datasets"
namespace: "workflows"
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf
dependencies:
  - name: validation/check_dataset_with_schema
    repository: openproblems
  - name: utils/extract_uns_metadata
    repository: openproblems
  - name: data_processors/process_dataset
runners:
  - type: nextflow
