__merge__: /src/api/comp_process_datasets.yaml
name: "process_datasets"
namespace: "workflows"
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf
dependencies:
  - name: common/check_dataset_schema
    repository: openproblems_v2
  - name: common/extract_metadata
    repository: openproblems_v2
  - name: data_processors/process_dataset
runners:
  - type: nextflow
