__merge__: ../../../api/comp_method.yaml
name: novel
label: Novel
summary: A method using encoder-decoder MLP model
description: This method trains an encoder-decoder MLP model with one output neuron per component in the target. As an input, the encoders use representations obtained from ATAC and GEX data via LSI transform and raw ADT data. The hyperparameters of the models were found via broad hyperparameter search using the Optuna framework.
references:
  doi:
    - 10.1101/2022.04.11.487796
links:
  documentation: https://github.com/openproblems-bio/neurips2021_multimodal_topmethods/tree/main/src/predict_modality/methods/novel#readme
  repository: https://github.com/openproblems-bio/neurips2021_multimodal_topmethods/tree/main/src/predict_modality/methods/novel
info:
  submission_id: "169769"
  preferred_normalization: log_cp10k
resources:
  - path: main.nf
    type: nextflow_script
    entrypoint: run_wf
dependencies:
  - name: methods/novel_train
  - name: methods/novel_predict
runners:
  - type: nextflow 