__merge__: ../../../api/comp_method_train.yaml
name: novel_train
arguments:
  - name: "--seed"
    type: "integer"
    description: "Seed for choosing the internal validation batches, when the dataset does not contain the batches used in the competition."
    default: 1
resources:
  - path: script.py
    type: python_script
  - path: ../helper_functions.py
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1
    setup:
      - type: python
        packages:
          - scikit-learn
          - networkx
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, hightime, midcpu, highsharedmem, gpu] 
