name: "run_benchmark"
namespace: "workflows"
argument_groups:
  - name: Inputs
    arguments:
      - name: "--input_train_mod1"
        __merge__: /src/api/file_train_mod1.yaml
        required: true
        direction: input
      - name: "--input_train_mod2"
        __merge__: /src/api/file_train_mod2.yaml
        required: true
        direction: input
      - name: "--input_test_mod1"
        __merge__: /src/api/file_test_mod1.yaml
        required: true
        direction: input
      - name: "--input_test_mod2"
        __merge__: /src/api/file_test_mod2.yaml
        required: true
        direction: input
  - name: Outputs
    arguments:
      - name: "--output_scores"
        type: file
        required: true
        direction: output
        description: A yaml file containing the scores of each of the methods
        default: score_uns.yaml
      - name: "--output_method_configs"
        type: file
        required: true
        direction: output
        default: method_configs.yaml
      - name: "--output_metric_configs"
        type: file
        required: true
        direction: output
        default: metric_configs.yaml
      - name: "--output_dataset_info"
        type: file
        required: true
        direction: output
        default: dataset_uns.yaml
      - name: "--output_task_info"
        type: file
        required: true
        direction: output
        default: task_info.yaml
  - name: Methods
    arguments:
      - name: "--method_ids"
        type: string
        multiple: true
        description: A list of method ids to run. If not specified, all methods will be run.
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - type: file
    path: /_viash.yaml
dependencies:
  - name: common/check_dataset_schema
    repository: openproblems_v2
  - name: common/extract_metadata
    repository: openproblems_v2
  - name: control_methods/mean_per_gene
  - name: control_methods/random_predict
  - name: control_methods/zeros
  - name: control_methods/solution
  - name: methods/knnr_py
  - name: methods/knnr_r
  - name: methods/lm
  - name: methods/lmds_irlba_rf
  - name: methods/guanlab_dengkw_pm
  - name: methods/simple_mlp
  - name: metrics/correlation
  - name: metrics/mse
runners:
  - type: nextflow