__merge__: /src/api/comp_method_predict.yaml
name: scbutterfly_predict
info:
  test_setup:
    with_model:
      input_train_mod1: resources_test/task_predict_modality/openproblems_neurips2021/bmmc_multiome/swap/train_mod1.h5ad
      input_train_mod2: resources_test/task_predict_modality/openproblems_neurips2021/bmmc_multiome/swap/train_mod2.h5ad
      input_test_mod1: resources_test/task_predict_modality/openproblems_neurips2021/bmmc_multiome/swap/test_mod1.h5ad
      input_model: resources_test/task_predict_modality/openproblems_neurips2021/bmmc_multiome/swap/models/scbutterfly
resources:
  - path: script.py
    type: python_script
  - path: ../butterfly_common.py
  - path: ../chrom_utils.py
  - path: /src/utils/exit_codes.py
test_resources:
  - path: /resources_test/task_predict_modality/openproblems_neurips2021/bmmc_multiome/swap
    dest: resources_test/task_predict_modality/openproblems_neurips2021/bmmc_multiome/swap
engines:
  - type: docker
    image: python:3.9
    setup:
      - type: docker
        run:
          - pip install --no-cache-dir torch==1.13.1 torchvision==0.14.1 --index-url https://download.pytorch.org/whl/cu117
          - pip install --no-cache-dir --no-deps scButterfly
          - pip install --no-cache-dir "numpy==1.23.5" "scipy==1.9.3" "pandas<2" "scanpy==1.9.3" "anndata==0.8.0" "scikit-learn>=1.1" numba tqdm matplotlib adjustText bamnostic pysam legacy-api-wrap
          - pip install --no-cache-dir --no-deps episcanpy==0.3.2
          - pip install --no-cache-dir "git+https://github.com/openproblems-bio/core.git#subdirectory=packages/python/openproblems"
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, hightime, midcpu, gpu]
