__merge__: ../../api/comp_method.yaml
name: cellmapper_scvi
label: CellMapper+scVI
summary: "Modality prediction in an scVI latent space using CellMapper"
description: |
  CellMapper is a general framework for k-NN based mapping tasks in single-cell and spatial genomics.
  This variant uses CellMapper to project modalities from a reference dataset (train) onto a query dataset 
  (test) in a modality-specific latent space computed with suitable scvi-tools models. For gene expression data, 
  we use the scVI model on raw counts (nb likelihood), for ADT data, we use the scVI models on normalized counts 
  (gaussian likelihood), and for ATAC data, we use the PeakVI model on raw counts. The actual CellMapper pipeline is 
  modality-agnostic. 
references:
  doi: 
    - 10.5281/zenodo.15683594
links:
  documentation: https://cellmapper.readthedocs.io/en/latest/
  repository: https://github.com/quadbio/cellmapper
info:
  preferred_normalization: log_cp10k
  variants: 
    cellmapper_hnoca_hvg:
      kernel_method: hnoca
      use_hvg: true
      adt_normalization: clr
    cellmapper_hnoca_all_genes:
      kernel_method: hnoca
      use_hvg: false
      adt_normalization: clr
    cellmapper_gauss_hvg:
      kernel_method: gauss
      use_hvg: true
      adt_normalization: clr
    cellmapper_gauss_hvg_log_cp10k:
      kernel_method: gauss
      use_hvg: true
      adt_normalization: log_cp10k
    cellmapper_gauss_all_genes:
      kernel_method: gauss
      use_hvg: false
      adt_normalization: clr

arguments:
  - name: "--kernel_method"
    type: "string"
    choices: ["hnoca", "gauss"]
    default: "gauss"
    description: Kernel function to compute k-NN edge weights (CellMapper parameter). 
  - name: "--n_neighbors"
    type: "integer"
    default: 50
    description: Number of neighbors to consider for k-NN graph construction (CellMapper parameter).
  - name: "--use_hvg"
    type: boolean
    default: true
    description: Whether to use highly variable genes (HVG) for the mapping (Generic analysis parameter).
  - name: "--adt_normalization"
    type: "string"
    choices: ["clr", "log_cp10k"]
    default: "clr"
    description: Normalization method for ADT data, clr = centered log ratio. 
  - name: "--plot_umap"
    type: boolean
    default: false
    description: Whether to plot the UMAP embedding of the latent space (for diagnoscic purposes)
resources:
  - type: python_script
    path: script.py
  - path: utils.py
    dest: utils.py 
engines:
  - type: docker
    image: openproblems/base_pytorch_nvidia:1.0.0
    setup:
      - type: python
        packages: 
          - cellmapper>=0.2.2
          - scvi-tools>=1.3.0
          - muon>=0.1.6

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu,gpu]
